### ISSUE TITLE
大佬，有DSP_2808_APP的例程吗？

### ISSUE THREAD

**Issue by a1292999652** [596142041/TMS32F2808_Bootloader#1]
内存映射部分总是设不正确，接触DSP没多久的菜鸟一枚

**Comment by 596142041** [comment]
详见https://github.com/596142041/TMS320F2808_APP，这是正常使用2808的app

**Comment by a1292999652** [comment]
> 见[https://github.com/596142041/TMS320F2808_APP，这是正常使用2808的app](https://github.com/596142041/TMS320F2808_APP%EF%BC%8C%E8%BF%99%E6%98%AF%E6%AD%A3%E5%B8%B8%E4%BD%BF%E7%94%A82808%E7%9A%84app)

和上位机通讯上了，非常感谢！
